lxodud/TimePaper

- frontend/src/constant/staticImagePath.js
> [SSD-72] imagePath 에러 수정

- frontend/src/router/index.jsx
- SSD-74
/timepaper로 이동시 /로 이동시켰으나 /timepaper가 URL에 남는 현상 개선을 위한 코드로 Navigate 사용
- [✅] 커밋 메시지에 Jira 이슈 번호 포함
- [✅] Jira 이슈 상태 업데이트
> [SSD-74] router /timepaper element Navigate로 변경

- frontend/src/pages/timepaperlocked/TimePaperIsLocked.jsx
- frontend/src/pages/timepaperlocked/TimePaperIsLocked.module.css
- frontend/src/router/index.jsx
> [SSD-66] 타임페이퍼 잠금 페이지 구현

- frontend/src/css/index.css
- frontend/src/pages/NotFound.jsx
- frontend/src/pages/error/NotFound.jsx
- frontend/src/pages/error/NotFound.module.css
- frontend/src/router/index.jsx
- SSD-65
- 존재하지 않는 URL 요청 시 반환할 에러 페이지를 구현
> [SSD-65] 에러페이지 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/pages/Home.jsx
- frontend/src/pages/home/Home.jsx
- frontend/src/pages/home/Home.module.css
- frontend/src/pages/login/Login.module.css
- frontend/src/router/index.jsx
- frontend/src/store/slices/authSlice.js
- frontend/src/store/store.js
- SSD-56
- Home 페이지 UI, 로직 구현
- 
- authSlice 쪽 수정사항 있습니다!
> [SSD-56] 홈 화면 구현

- backend/.gitignore
- backend/src/main/java/com/timepaper/backend/domain/my/dto/response/MyTimepaperListResponseDto.java
- backend/src/main/java/com/timepaper/backend/domain/user/controller/TestController.java
- frontend/src/router/index.jsx
- SSD-101
- 로그인 API 테스트를 위한 회원가입 임시 API
- TimepaperDetail 경로 수정(#35 )
> [SSD-101] chore: 로그인 API 테스트를 위한 회원가입 임시 API

- .github/workflows/deploy.yml
- backend/Dockerfile
- backend/src/main/java/com/timepaper/backend/global/config/WebConfig.java
- backend/src/main/resources/application.properties
- docker-compose.yml
- frontend/Dockerfile
- frontend/nginx.conf
- frontend/templates/default.conf.template
- frontend/templates/https.conf.template
- SSD-95
- 회원가입 페이지 구현
- 노드 추가 패키지 설치
> [SSD-95] 배포 세팅

- frontend/src/pages/PostItCreate.jsx
- frontend/src/pages/postitcreate/PostItCreate.jsx
- frontend/src/pages/postitcreate/PostItCreate.module.css
- frontend/src/router/index.jsx
- SSD-91
- 포스트잇 생성 페이지 구현
- 헤더는 공통 헤더 미 구현 상태입니다.
> [SSD-91] 포스트잇 생성 페이지 구현

- backend/src/main/java/com/timepaper/backend/domain/my/controller/MyController.java
- backend/src/main/java/com/timepaper/backend/domain/my/dto/response/MyInfoResponseDto.java
- backend/src/main/java/com/timepaper/backend/domain/my/dto/response/MyTimepaperListResponseDto.java
- backend/src/main/java/com/timepaper/backend/domain/my/repository/MyInfoRepository.java
- backend/src/main/java/com/timepaper/backend/domain/my/service/MyService.java
- package-lock.json
- package.json
- SSD-97 
로그인시-내-정보-조회-API-구현-refactor
- 노드 추가 패키지 설치
> [SSD-97] 로그인시 내 정보 조회 API 구현

- frontend/src/App.jsx
- frontend/src/api/api.js
- frontend/src/main.jsx
- frontend/src/pages/login/Login.jsx
- frontend/src/store/slices/authSlice.js
- SSD-109 
- 로그인된 사용자 정보 email, role 상태 관리 추가
> [SSD-109] 로그인 시 유저 정보 api 호출 및 redux 상태 저장

- frontend/src/api/api.js
- frontend/src/layout/RootLayout.jsx
- frontend/src/layout/RootLayout.module.css
- frontend/src/pages/login/Login.jsx
- frontend/src/store/slices/authSlice.js
- SSD-111
- 로그아웃 API 연동
- 로그인된 사용자에 대해 로그아웃 기능 구현
- 로그아웃 시 accessToken, isLoggedIn Redux 상태 관리 처리 
- 로그아웃 버튼 위치 미정
- 개발 및 테스트 과정에서 로그아웃 기능이 없어 불편함 발생
- 임시로 로그인 상태에서 footer에 로그아웃 버튼이 나타나도록 구현
- 최종 배치는 추후 회의 후 결정 
- 백엔드 로그아웃 API 를 반영 후 테스트해봐야 정상 동작합니다.
> [SSD-111] 로그아웃 api 연동

- frontend/src/App.jsx
- frontend/src/store/slices/authSlice.js
> [SSD-113]사용자 정보 상태 관리 수정

- .github/workflows/deploy.yml
- .gitignore
- docker-compose-local.yml
- frontend/Dockerfile.local
- frontend/conf.d/default.conf
- SSD-122
- 테스트를 위한 로컬 Deploy 환경 구성
> [SSD-122] 로컬 ci cd 구성

- frontend/src/pages/time-paper-detail/TimePaperDetail.jsx
- SSD-129
- 타임페이퍼 페이지에서 포스트잇 생성 페이지 이동 연결
> [SSD-129] feat: 타임페이퍼 페이지에서 포스트잇 페이지 연동

- frontend/src/pages/time-paper-create/TimePaperCreate.jsx
- SSD-123
- 타임페이퍼 생성시 해당 타임페이퍼로 이동하지 않는 에러 수정
- sumbit navigate 수정
- - 타이틀에 공백을 넣을 때 에러메세지를 보여주는 로직 추가
> [SSD-123] 타임페이퍼 생성 예외 처리

- .github/workflows/deploy.yml
- backend/src/main/java/com/timepaper/backend/global/config/WebConfig.java
- backend/src/main/resources/application.properties
- docker-compose.yml
> [SSD-131] 배포파일 환경변수 추가

- .github/workflows/deploy.yml
- backend/src/main/java/com/timepaper/backend/domain/postit/service/PostitService.java
- backend/src/main/java/com/timepaper/backend/global/auth/filter/LoginFilter.java
- backend/src/main/java/com/timepaper/backend/global/exception/ErrorCode.java
- backend/src/main/java/com/timepaper/backend/global/exception/custom/common/ForBiddenException.java
- backend/src/main/java/com/timepaper/backend/global/exception/custom/common/ResourceNotFoundException.java
- backend/src/main/java/com/timepaper/backend/global/exception/custom/timepaper/ResourceNotFoundException.java
- backend/src/main/java/com/timepaper/backend/global/exception/handler/GlobalExceptionHandler.java
> [SSD-133] 포스트잇 예외 처리

- backend/src/main/java/com/timepaper/backend/domain/user/repository/UserRepository.java
- backend/src/main/java/com/timepaper/backend/global/auth/filter/LoginFilter.java
- backend/src/main/java/com/timepaper/backend/global/auth/service/AuthService.java
- backend/src/main/java/com/timepaper/backend/global/auth/token/service/RefreshTokenService.java
- backend/src/main/java/com/timepaper/backend/global/auth/token/util/JWTUtil.java
- frontend/src/store/slices/authSlice.js
- SSD-136
- JWT payload에 userId 추가
- client auth slice 상태관리에 userID 추가
- 포스트잇, 롤링페이퍼 작성자 관리에 필요하여 추가하였습니다. 
- 중복 코드 정리 등은 추후 수정하겠습니다.
> [SSD-136] JWT payload 추가

- frontend/src/components/Alert/Alert.module.css
- frontend/src/components/BottomButton/BottomButton.jsx
- frontend/src/components/Loading/Loading.module.css
- frontend/src/pages/home/Home.jsx
- frontend/src/pages/login/Login.jsx
- frontend/src/pages/login/Login.module.css
- frontend/src/pages/signup/SignUp.jsx
- frontend/src/pages/signup/SignUp.module.css
- SSD-137
- 로그인, 홈 페이지 CSS 수정
- Alert 코드 추가
> [SSD-137] 홈 로그인 페이지 예외처리

- backend/src/main/java/com/timepaper/backend/domain/timepaper/service/TimePaperService.java
- backend/src/main/java/com/timepaper/backend/global/auth/filter/LoginFilter.java
- backend/src/main/java/com/timepaper/backend/global/auth/token/service/RefreshTokenService.java
- backend/src/main/java/com/timepaper/backend/global/exception/ErrorCode.java
- backend/src/main/java/com/timepaper/backend/global/s3/service/S3Service.java
- SSD-140
- 유저 관련 예외시 클라이언트 응답 공통화 
- 파일 업로드, 실패 예외 발생시 클라이언트 응답 공통화
> [SSD-140] 유저 관련 예외 처리

- frontend/src/components/Alert/Alert.module.css
- frontend/src/components/BottomButton/BottomButton.jsx
- frontend/src/pages/login/Login.jsx
- frontend/src/pages/login/Login.module.css
- frontend/src/pages/signup/SignUp.jsx
- frontend/src/pages/signup/SignUp.module.css
- frontend/src/pages/time-paper-create/TimePaperCreate.jsx
- frontend/src/pages/time-paper-create/TimePaperCreate.module.css
- SSD-141
- Alert 크기 변경
- 타임페이퍼 생성 페이지 Alert 추가
> [SSD-141] 타임페이퍼 생성 페이지 예외처리

- backend/src/main/java/com/timepaper/backend/domain/timepaper/dto/response/TimePaperResponseDto.java
- frontend/src/components/Modal/Modal.jsx
- frontend/src/components/dropdownmenu/Dropdown.jsx
- frontend/src/pages/time-paper-detail/TimePaperDetail.jsx
- SSD-142
- 타임페이퍼 캡슐화, 삭제 버튼 로그인된 유저id에 따른 invisible 처리
- 포스트잇 삭제 버튼 로그인된 유저id에 따른 invisible 처리
> [SSD-142] 타임페이퍼 캡슐화 삭제 포스트잇 삭제 버튼 사용자에 따른 invisible 처리

- frontend/src/components/UnderBarInput/UnderBarInput.jsx
- frontend/src/pages/postit-create/PostItCreate.jsx
- frontend/src/pages/postit-create/PostItCreate.module.css
- frontend/src/pages/time-paper-create/TimePaperCreate.jsx
- SSD-150
- Postit Create 페이지 수정
> [SSD-150] 포스트잇 생성 페이지 예외처리

- frontend/src/pages/time-paper-detail/TimePaperDetail.jsx
- frontend/src/pages/time-paper-detail/TimePaperDetail.module.css
- frontend/src/pages/time-paper-set-lock/TimePaperSetLock.jsx
- SSD-152
- 타임페이퍼 잠금(캡슐화) 페이지 예외처리
- 타임페이퍼 디테일 css 일부 수정
> [SSD-152] feat: 타임페이퍼 잠금 페이지 예외처리
